### ISSUE TITLE
It would be nice to generate charts artifacts from Maven build

### ISSUE THREAD

**Issue by introproventures** [introproventures/demo#3]
Given:
```
@project.artifactId@=demo
@project.version@=0.1.0
@dockerfile.repository@=introproventures/demo 
@dockerfile.tag@=@project.version@

    <properties>	
    	<dockerfile.repository>${project.artifactId}</dockerfile.repository>
    	<dockerfile.tag>${project.version}</dockerfile.tag>
    </properties>
```
``` 
# Chart.yaml resource template
apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: "@project.artifactId@"
version: "@project.version@"
```

```
# values.yaml resource template
# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: @dockerfile.repository@
  tag: @dockerfile.tag@
  pullPolicy: IfNotPresent
service:
  name: @project.artifactId@
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
```

When:
```
mvn clean package -Ddockerfile.repository=introproventures/demo -Ddockerfile.tag=0.1.0
```

Then:
```
# Generated Chart.yaml
apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: "demo"
version: "0.1.0"
```

```
# Generated values.yaml
# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: introproventures/demo
  tag: 0.1.0
  pullPolicy: IfNotPresent
service:
  name: @project.artifactId@
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
```
